-- =====================================================================
-- V1: Tablas base sin relaciones (Categoria y Analista)
-- =====================================================================

CREATE TABLE categoria (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255),
    CONSTRAINT uq_categoria_nombre UNIQUE (nombre)
);

CREATE TABLE analista (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    correo VARCHAR(180) NOT NULL,
    CONSTRAINT uq_analista_correo UNIQUE (correo)
);
