-- =====================================================================
-- V2: Tabla evento (relacion con categoria, enums, soft delete)
-- =====================================================================

CREATE TABLE evento (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo       VARCHAR(30)  NOT NULL,
    titulo       VARCHAR(200) NOT NULL,
    descripcion  TEXT,
    fecha        TIMESTAMP    NOT NULL,
    prioridad    VARCHAR(20)  NOT NULL,
    estado       VARCHAR(30)  NOT NULL,
    fuente       VARCHAR(150),
    categoria_id BIGINT       NOT NULL,
    activo       BOOLEAN      NOT NULL DEFAULT TRUE,

    CONSTRAINT uq_evento_codigo UNIQUE (codigo),

    -- Integridad referencial: no se puede borrar una categoria con eventos
    CONSTRAINT fk_evento_categoria FOREIGN KEY (categoria_id)
        REFERENCES categoria (id) ON DELETE RESTRICT
);

-- Indices para acelerar filtros y busquedas frecuentes (grandes volumenes)
CREATE INDEX idx_evento_categoria ON evento (categoria_id);
CREATE INDEX idx_evento_estado    ON evento (estado);
CREATE INDEX idx_evento_prioridad ON evento (prioridad);
CREATE INDEX idx_evento_fecha     ON evento (fecha);
CREATE INDEX idx_evento_activo    ON evento (activo);
