-- =====================================================================
-- V4: Tablas asignacion (evento<->analista) e historial_evento (auditoria)
-- =====================================================================

CREATE TABLE asignacion (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id        BIGINT      NOT NULL,
    analista_id      BIGINT      NOT NULL,
    fecha_asignacion TIMESTAMP   NOT NULL,
    estado           VARCHAR(20) NOT NULL,

    -- Evita asignaciones duplicadas del mismo evento al mismo analista
    CONSTRAINT uq_asignacion_evento_analista UNIQUE (evento_id, analista_id),

    CONSTRAINT fk_asignacion_evento FOREIGN KEY (evento_id)
        REFERENCES evento (id) ON DELETE RESTRICT,
    CONSTRAINT fk_asignacion_analista FOREIGN KEY (analista_id)
        REFERENCES analista (id) ON DELETE RESTRICT
);

CREATE INDEX idx_asignacion_evento   ON asignacion (evento_id);
CREATE INDEX idx_asignacion_analista ON asignacion (analista_id);


CREATE TABLE historial_evento (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id  BIGINT      NOT NULL,
    usuario    VARCHAR(150) NOT NULL,
    fecha      TIMESTAMP    NOT NULL,
    accion     VARCHAR(30)  NOT NULL,
    comentario VARCHAR(500),

    CONSTRAINT fk_historial_evento FOREIGN KEY (evento_id)
        REFERENCES evento (id) ON DELETE RESTRICT
);

CREATE INDEX idx_historial_evento ON historial_evento (evento_id);
